/**
 * Privacy Policy Page
 * Internal page to keep users within the quiz experience
 */

import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import styles from './Quiz.module.css';

export const PrivacyPolicy = () => {
  const navigate = useNavigate();

  const handleBack = () => {
    navigate(-1);
  };

  return (
    <div className={`${styles.quizContainer} ${styles.quizContainerRelative}`}>
      <button className={styles.backArrow} onClick={handleBack} aria-label="Go back">
        ←
      </button>
      <motion.div
        className={styles.quizContent}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        style={{ maxWidth: '900px' }}
      >
        <h1 className={styles.headline}>Privacy Policy</h1>
        <p style={{ color: 'rgba(107, 114, 128, 1)', marginBottom: '32px', textAlign: 'center' }}>
          Last updated: June 30, 2025
        </p>

        <div className={styles.legalContent}>
          <p className={styles.bodyText}>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className={styles.bodyText}>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className={styles.legalHeading}>Interpretation and Definitions</h2>
          
          <h3 className={styles.legalSubheading}>Interpretation</h3>
          <p className={styles.bodyText}>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className={styles.legalSubheading}>Definitions</h3>
          <p className={styles.bodyText}>For the purposes of this Privacy Policy:</p>
          <ul className={styles.legalList}>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Business</strong>, for the purpose of CCPA/CPRA, refers to the Company as the legal entity that collects Consumers' personal information and determines the purposes and means of the processing of Consumers' personal information.</li>
            <li><strong>CCPA and/or CPRA</strong> refers to the California Consumer Privacy Act (the "CCPA") as amended by the California Privacy Rights Act of 2020 (the "CPRA").</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Wellness In Weeks LLC, 1226 NW Rockwood LN. Bend, OR. 97703.</li>
            <li><strong>Consumer</strong>, for the purpose of the CCPA/CPRA, means a natural person who is a California resident.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Oregon, United States</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Do Not Track (DNT)</strong> is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to Wellness In Weeks, accessible from https://wellnessinweeks.com/</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className={styles.legalHeading}>Collecting and Using Your Personal Data</h2>
          
          <h3 className={styles.legalSubheading}>Types of Data Collected</h3>
          <h4 style={{ fontSize: '1rem', fontWeight: '600', color: 'rgba(29, 44, 73, 1)', margin: '16px 0 8px' }}>Personal Data</h4>
          <p className={styles.bodyText}>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className={styles.legalList}>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Bank account information in order to pay for products and/or services within the Service</li>
            <li>Usage Data</li>
          </ul>
          <p className={styles.bodyText}>
            When You pay for a product and/or a service via bank transfer, We may ask You to provide information to facilitate this transaction and to verify Your identity. Such information may include, without limitation:
          </p>
          <ul className={styles.legalList}>
            <li>Date of birth</li>
            <li>Passport or National ID card</li>
            <li>Bank card statement</li>
            <li>Other information linking You to an address</li>
          </ul>

          <h4 style={{ fontSize: '1rem', fontWeight: '600', color: 'rgba(29, 44, 73, 1)', margin: '16px 0 8px' }}>Usage Data</h4>
          <p className={styles.bodyText}>
            Usage Data is collected automatically when using the Service.
          </p>
          <p className={styles.bodyText}>
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p className={styles.bodyText}>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>

          <h3 className={styles.legalSubheading}>Tracking Technologies and Cookies</h3>
          <p className={styles.bodyText}>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <ul className={styles.legalList}>
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
          </ul>
          <p className={styles.bodyText}>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
          </p>
          <p className={styles.bodyText}>
            We use both Session and Persistent Cookies for the purposes set out below:
          </p>
          <ul className={styles.legalList}>
            <li><strong>Necessary / Essential Cookies</strong> - Type: Session Cookies - Administered by: Us - Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
            <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> - Type: Persistent Cookies - Administered by: Us - Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
            <li><strong>Functionality Cookies</strong> - Type: Persistent Cookies - Administered by: Us - Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
          </ul>

          <h2 className={styles.legalHeading}>Use of Your Personal Data</h2>
          <p className={styles.bodyText}>The Company may use Personal Data for the following purposes:</p>
          <ul className={styles.legalList}>
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>To deliver targeted advertising to You:</strong> We may use Your information to develop and display content and advertising tailored to Your interests.</li>
            <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
          </ul>

          <h2 className={styles.legalHeading}>Retention of Your Personal Data</h2>
          <p className={styles.bodyText}>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p className={styles.bodyText}>
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service.
          </p>

          <h2 className={styles.legalHeading}>Transfer of Your Personal Data</h2>
          <p className={styles.bodyText}>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
          </p>
          <p className={styles.bodyText}>
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
          </p>
          <p className={styles.bodyText}>
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
          </p>

          <h2 className={styles.legalHeading}>Delete Your Personal Data</h2>
          <p className={styles.bodyText}>
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
          </p>
          <p className={styles.bodyText}>
            Our Service may give You the ability to delete certain information about You from within the Service.
          </p>
          <p className={styles.bodyText}>
            You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>
          <p className={styles.bodyText}>
            Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
          </p>

          <h2 className={styles.legalHeading}>Disclosure of Your Personal Data</h2>
          <h3 className={styles.legalSubheading}>Business Transactions</h3>
          <p className={styles.bodyText}>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>
          <h3 className={styles.legalSubheading}>Law enforcement</h3>
          <p className={styles.bodyText}>
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>
          <h3 className={styles.legalSubheading}>Other legal requirements</h3>
          <p className={styles.bodyText}>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className={styles.legalList}>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h2 className={styles.legalHeading}>Security of Your Personal Data</h2>
          <p className={styles.bodyText}>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h2 className={styles.legalHeading}>Detailed Information on the Processing of Your Personal Data</h2>
          <p className={styles.bodyText}>
            The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.
          </p>

          <h3 className={styles.legalSubheading}>Payments</h3>
          <p className={styles.bodyText}>
            We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).
          </p>
          <p className={styles.bodyText}>
            We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council.
          </p>
          <ul className={styles.legalList}>
            <li><strong>Stripe</strong> - Their Privacy Policy can be viewed at https://stripe.com/us/privacy</li>
            <li><strong>PayPal</strong> - Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full</li>
          </ul>

          <h3 className={styles.legalSubheading}>Behavioral Remarketing</h3>
          <p className={styles.bodyText}>
            The Company uses remarketing services to advertise to You after You accessed or visited our Service. We and Our third-party vendors use cookies and non-cookie technologies to help Us recognize Your Device and understand how You use our Service so that We can improve our Service to reflect Your interests and serve You advertisements that are likely to be of more interest to You.
          </p>
          <p className={styles.bodyText}>
            You may opt-out of all personalized advertising by enabling privacy features on Your mobile device such as Limit Ad Tracking (iOS) and Opt Out of Ads Personalization (Android).
          </p>
          <p className={styles.bodyText}>The third-party vendors We use are:</p>
          <ul className={styles.legalList}>
            <li><strong>Google Ads (AdWords)</strong> - You can opt-out of Google Analytics for Display Advertising by visiting the Google Ads Settings page: http://www.google.com/settings/ads</li>
            <li><strong>Twitter</strong> - You can opt-out from Twitter's interest-based ads by following their instructions: https://support.twitter.com/articles/20170405</li>
            <li><strong>Facebook</strong> - You can learn more about interest-based advertising from Facebook by visiting: https://www.facebook.com/help/516147308587266</li>
          </ul>

          <h2 className={styles.legalHeading}>CCPA/CPRA Privacy Notice (California Privacy Rights)</h2>
          <p className={styles.bodyText}>
            This privacy notice section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.
          </p>

          <h3 className={styles.legalSubheading}>Categories of Personal Information Collected</h3>
          <p className={styles.bodyText}>
            We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular Consumer or Device.
          </p>

          <h3 className={styles.legalSubheading}>Your Rights under the CCPA/CPRA</h3>
          <p className={styles.bodyText}>
            The CCPA/CPRA provides California residents with specific rights regarding their personal information. If You are a resident of California, You have the following rights:
          </p>
          <ul className={styles.legalList}>
            <li><strong>The right to notice.</strong> You have the right to be notified which categories of Personal Data are being collected and the purposes for which the Personal Data is being used.</li>
            <li><strong>The right to know/access.</strong> Under CCPA/CPRA, You have the right to request that We disclose information to You about Our collection, use, sale, disclosure for business purposes and share of personal information.</li>
            <li><strong>The right to say no to the sale or sharing of Personal Data (opt-out).</strong> You have the right to direct Us to not sell Your personal information.</li>
            <li><strong>The right to correct Personal Data.</strong> You have the right to correct or rectify any inaccurate personal information about You that We collected.</li>
            <li><strong>The right to limit use and disclosure of sensitive Personal Data.</strong> You have the right to request to limit the use or disclosure of certain sensitive personal information We collected about You.</li>
            <li><strong>The right to delete Personal Data.</strong> You have the right to request the deletion of Your Personal Data under certain circumstances, subject to certain exceptions.</li>
            <li><strong>The right not to be discriminated against.</strong> You have the right not to be discriminated against for exercising any of Your consumer's rights.</li>
          </ul>

          <h3 className={styles.legalSubheading}>Exercising Your CCPA/CPRA Data Protection Rights</h3>
          <p className={styles.bodyText}>
            In order to exercise any of Your rights under the CCPA/CPRA, and if You are a California resident, You can contact Us by email: support@wellnessinweeks.com
          </p>
          <p className={styles.bodyText}>
            Only You, or a person registered with the California Secretary of State that You authorize to act on Your behalf, may make a verifiable request related to Your personal information.
          </p>

          <h3 className={styles.legalSubheading}>Do Not Sell My Personal Information</h3>
          <p className={styles.bodyText}>
            We do not sell personal information as the term sell is commonly understood. We do allow Service Providers to use Your personal information for the business purposes described in Our Privacy Policy, for activities such as advertising, marketing, and analytics, and these may be deemed a sale under CCPA/CPRA.
          </p>
          <p className={styles.bodyText}>
            You have the right to opt-out of the sale of Your personal information. Once We receive and confirm a verifiable consumer request from You, we will stop selling Your personal information. To exercise Your right to opt-out, please contact Us.
          </p>

          <h2 className={styles.legalHeading}>"Do Not Track" Policy as Required by California Online Privacy Protection Act (CalOPPA)</h2>
          <p className={styles.bodyText}>
            Our Service does not respond to Do Not Track signals.
          </p>
          <p className={styles.bodyText}>
            However, some third party websites do keep track of Your browsing activities. If You are visiting such websites, You can set Your preferences in Your web browser to inform websites that You do not want to be tracked.
          </p>

          <h2 className={styles.legalHeading}>Children's Privacy</h2>
          <p className={styles.bodyText}>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
          </p>
          <p className={styles.bodyText}>
            If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>

          <h2 className={styles.legalHeading}>Links to Other Websites</h2>
          <p className={styles.bodyText}>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p className={styles.bodyText}>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>

          <h2 className={styles.legalHeading}>Changes to this Privacy Policy</h2>
          <p className={styles.bodyText}>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className={styles.bodyText}>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p className={styles.bodyText}>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>

          <h2 className={styles.legalHeading}>Contact Us</h2>
          <p className={styles.bodyText}>
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <p className={styles.bodyText}>
            <strong>By email:</strong> support@wellnessinweeks.com
          </p>
        </div>
      </motion.div>
    </div>
  );
};

export default PrivacyPolicy;
